USE [ilfl]
GO
/****** Object:  Table [dbo].[IFCTContent]    Script Date: 6/12/2024 7:42:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IFCTContent](
	[IFCTId] [int] IDENTITY(1,1) NOT NULL,
	[IFCT_IFSS] [int] NOT NULL,
	[IFCTDisplayName] [varchar](100) NOT NULL,
	[IFCTDescription] [varchar](100) NULL,
	[IFCTFile] [varchar](max) NOT NULL,
 CONSTRAINT [PK_IFCTContent] PRIMARY KEY CLUSTERED 
(
	[IFCTId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IFPCPageContent]    Script Date: 6/12/2024 7:42:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IFPCPageContent](
	[IFPCId] [int] IDENTITY(1,1) NOT NULL,
	[IFPC_IFSSId] [int] NOT NULL,
	[IFPC_HTML_Content] [varchar](max) NULL,
 CONSTRAINT [PK_IFPCPageContent] PRIMARY KEY CLUSTERED 
(
	[IFPCId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IFSSSection]    Script Date: 6/12/2024 7:42:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IFSSSection](
	[IFSSId] [int] IDENTITY(1,1) NOT NULL,
	[IFSSParent] [int] NULL,
	[IFSSName] [varchar](100) NOT NULL,
	[IFSSPath] [varchar](150) NULL,
	[IFSSIsPageEditable] [bit] NOT NULL,
 CONSTRAINT [PK_IFSSSection] PRIMARY KEY CLUSTERED 
(
	[IFSSId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IFULUsers]    Script Date: 6/12/2024 7:42:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IFULUsers](
	[IFULId] [int] IDENTITY(1,1) NOT NULL,
	[IFULUsername] [varbinary](150) NOT NULL,
	[IFULPassword] [varbinary](150) NOT NULL,
 CONSTRAINT [PK_IFULUsers] PRIMARY KEY CLUSTERED 
(
	[IFULId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IFSSSection] ADD  CONSTRAINT [DF_IFSSSection_IFSSIsPageEditable]  DEFAULT ((0)) FOR [IFSSIsPageEditable]
GO
ALTER TABLE [dbo].[IFCTContent]  WITH CHECK ADD  CONSTRAINT [FK_IFCT_IFSS] FOREIGN KEY([IFCT_IFSS])
REFERENCES [dbo].[IFSSSection] ([IFSSId])
GO
ALTER TABLE [dbo].[IFCTContent] CHECK CONSTRAINT [FK_IFCT_IFSS]
GO
ALTER TABLE [dbo].[IFPCPageContent]  WITH CHECK ADD  CONSTRAINT [FK_IFPCPageContent_IFPCPageContent] FOREIGN KEY([IFPC_IFSSId])
REFERENCES [dbo].[IFSSSection] ([IFSSId])
GO
ALTER TABLE [dbo].[IFPCPageContent] CHECK CONSTRAINT [FK_IFPCPageContent_IFPCPageContent]
GO
