USE [master]
GO
/****** Object:  Database [ilfl]    Script Date: 5/4/2024 12:58:14 AM ******/
CREATE DATABASE [ilfl]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ilfl', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ilfl.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ilfl_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ilfl_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ilfl] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ilfl].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ilfl] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ilfl] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ilfl] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ilfl] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ilfl] SET ARITHABORT OFF 
GO
ALTER DATABASE [ilfl] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ilfl] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ilfl] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ilfl] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ilfl] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ilfl] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ilfl] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ilfl] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ilfl] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ilfl] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ilfl] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ilfl] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ilfl] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ilfl] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ilfl] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ilfl] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ilfl] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ilfl] SET RECOVERY FULL 
GO
ALTER DATABASE [ilfl] SET  MULTI_USER 
GO
ALTER DATABASE [ilfl] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ilfl] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ilfl] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ilfl] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ilfl] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ilfl] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ilfl', N'ON'
GO
ALTER DATABASE [ilfl] SET QUERY_STORE = OFF
GO
USE [ilfl]
GO
/****** Object:  Table [dbo].[IFCTContent]    Script Date: 5/4/2024 12:58:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IFCTContent](
	[IFCTId] [int] IDENTITY(1,1) NOT NULL,
	[IFCTDisplayName] [varchar](100) NOT NULL,
	[IFCTSection] [varchar](100) NOT NULL,
	[IFCTFile] [varchar](max) NOT NULL,
 CONSTRAINT [PK_IFCTContent] PRIMARY KEY CLUSTERED 
(
	[IFCTId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IFDDDirectorDetails]    Script Date: 5/4/2024 12:58:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IFDDDirectorDetails](
	[IFDDName] [varchar](100) NOT NULL,
	[IFDDPosition] [varchar](100) NOT NULL,
	[IFDDFile] [varchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IFULUsers]    Script Date: 5/4/2024 12:58:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IFULUsers](
	[IFULUsername] [varchar](10) NOT NULL,
	[IFULPassword] [varchar](10) NOT NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [ilfl] SET  READ_WRITE 
GO
