// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ilfl.Repositories.Entities;

public partial class Ifctcontent
{
    public int Ifctid { get; set; }

    public int IfctIfss { get; set; }

    public string IfctdisplayName { get; set; }

    public string Ifctfile { get; set; }

    public virtual Ifsssection IfctIfssNavigation { get; set; }
}