// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ilfl.Repositories.Entities;

public partial class IfdddirectorDetail
{
    public string Ifddname { get; set; }

    public string Ifddposition { get; set; }

    public string Ifddfile { get; set; }
}