// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ilfl.Repositories.Entities;

public partial class IfpcpageContent
{
    public int Ifpcid { get; set; }

    public int IfpcIfssid { get; set; }

    public string IfpcContent1 { get; set; }

    public string IfpcContent2 { get; set; }

    public string IfpcContent3 { get; set; }

    public string IfpcContent4 { get; set; }

    public string IfpcContent5 { get; set; }

    public string IfpcContent6 { get; set; }

    public string IfpcContent7 { get; set; }

    public virtual Ifsssection IfpcIfss { get; set; }
}