// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ilfl.Repositories.Entities;

public partial class Ifsssection
{
    public int Ifssid { get; set; }

    public int? Ifssparent { get; set; }

    public string Ifssname { get; set; }

    public string Ifsspath { get; set; }

    public virtual ICollection<Ifctcontent> Ifctcontents { get; set; } = new List<Ifctcontent>();
}