// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ilfl.Repositories.Entities;

public partial class Ifuluser
{
    public string Ifulusername { get; set; }

    public string Ifulpassword { get; set; }
}