// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ilfl.Repositories.Entities;

public partial class Ifuluser
{
    public int Ifulid { get; set; }

    public byte[] Ifulusername { get; set; }

    public byte[] Ifulpassword { get; set; }
}